version: '2'
services:
  app:
    image: gestvet
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@bhznk7s7igcpmya8_tp?TNS_ADMIN=/app/oracle_wallet
      - SPRING_DATASOURCE_USERNAME=GETVET_S6
      - SPRING_DATASOURCE_PASSWORD=Oraclecloud123
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_SHOW_SQL=true
      - TNS_ADMIN=/app/oracle_wallet
    networks:
      - default

networks:
  default:
    driver: bridge
